version: "3.3"
services:
  mariadb:
    image: mariadb:10.6.17-focal
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: adminer
      MYSQL_PASSWORD: adminer
      MYSQL_DATABASE: noinch
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 8080:8080
